{
 "title": "FFD Dashboard",
 "time": { "from": "2024-04-15T12:26:07.918Z", "to": "2024-04-15T13:05:51.990Z" },
 "panels": [
  {
   "title": "System Average Sent and Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(central_resources{source=\"system\", metric=\"NeSeBy\"})"
    },
    {
     "expr": "avg(central_resources{source=\"system\", metric=\"NeReBy\"})"
    }
   ]
  },
  {
   "title": "System Average Used CPU and RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(central_resources{metric=\"CPUPer\", source=\"system\"})"
    },
    {
     "expr": "avg(central_resources{metric=\"RAMPer\", source=\"system\"})"
    }
   ]
  },
  {
   "title": "Central and Workers Average CPU ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(worker_resources{source=\"server\", metric=\"CPUPer\"})"
    },
    {
     "expr": "avg(central_resources{source=\"server\", metric=\"CPUPer\"})"
    }
   ]
  },
  {
   "title": "Central and Workers Average Processing and Elapsed time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(central_times{metric=\"PrTiSec\"})"
    },
    {
     "expr": "avg(central_times{metric=\"ElTiSec\"})"
    },
    {
     "expr": "avg(worker_times{metric=\"ElTiSec\"})"
    },
    {
     "expr": "avg(worker_times{metric=\"PrTiSec\"})"
    }
   ]
  },
  {
   "title": "Central Average Task Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(central_times{metric=\"AcToSec\", source=\"system-monitoring\"})"
    },
    {
     "expr": "avg(central_times{metric=\"AcToSec\", source=\"server-monitoring\"})"
    },
    {
     "expr": "avg(central_times{metric=\"AcToSec\", source=\"data-pipeline\"})"
    },
    {
     "expr": "avg(central_times{metric=\"AcToSec\", source=\"update-pipeline\"})"
    },
    {
     "expr": "avg(central_times{metric=\"AcToSec\", source=\"aggregation-pipeline\"})"
    }
   ]
  },
  {
   "title": "Workers Average Task Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(worker_times{source=\"status-pipeline\", metric=\"AcToSec\"})"
    },
    {
     "expr": "avg(worker_times{source=\"data-pipeline\", metric=\"AcToSec\"})"
    },
    {
     "expr": "avg(worker_times{source=\"model-pipeline\", metric=\"AcToSec\"})"
    },
    {
     "expr": "avg(worker_times{source=\"update-pipeline\", metric=\"AcToSec\"})"
    },
    {
     "expr": "avg(worker_times{source=\"server-monitoring\", metric=\"AcToSec\"})"
    }
   ]
  }
 ]
}