version: '3.8'

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:      
  ffd-pushgateway:
    image: prom/pushgateway:v1.7.0
    restart: always
    ports:
      - '127.0.0.1:9091:9091'
    networks:
      app_network:
        ipv4_address: 172.28.0.5
  ffd-prometheus:
    image: t9k4b5ndjok1/ffd:prometheus
    restart: always
    ports:
      - '127.0.0.1:9090:9090'
    environment:
      - PROMETHEUS_TARGET='ffd-prometheus:9090'
      - PUSHGATEWAY_TARGET='ffd-pushgateway:9091'
      - CENTRAL_TARGET='ffd-central:7500'
      - WORKER_TARGET='ffd-worker-1:7501','ffd-worker-2:7501','ffd-worker-3:7501','ffd-worker-4:7501','ffd-worker-5:7501'
    networks:
      app_network:
        ipv4_address: 172.28.0.6
  ffd-grafana:
    image: t9k4b5ndjok1/ffd:grafana
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - PROMETHEUS_URL=http://ffd-prometheus:9090
    networks:
      app_network:
        ipv4_address: 172.28.0.7