global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [1]
  - job_name: 'pushgateway'
    static_configs:
      - targets: [2]
  - job_name: 'central'
    static_configs:
      - targets: [3]
  - job_name: 'workers'
    static_configs:
      - targets: [4]