version: '3.8'

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  ffd-postgres:
    image: t9k4b5ndjok1/ffd:postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      app_network:
        ipv4_address: 172.28.0.2
  ffd-minio:
    image: t9k4b5ndjok1/ffd:minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    networks:
      app_network:
        ipv4_address: 172.28.0.3
  ffd-mlflow:
    image: t9k4b5ndjok1/ffd:mlflow
    restart: always
    ports:
      - '5000:5000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - MLFLOW_S3_ENDPOINT_URL=http://ffd-minio:9000
      - MLFLOW_SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@ffd-postgres:5432/mlflow_db
    networks:
      app_network:
        ipv4_address: 172.28.0.4
  ffd-pushgateway:
    image: prom/pushgateway:v1.7.0
    restart: always
    ports:
      - '9091:9091'
    networks:
      app_network:
        ipv4_address: 172.28.0.5
  ffd-prometheus:
    image: t9k4b5ndjok1/ffd:prometheus
    restart: always
    ports:
      - '9090:9090'
    environment:
      - PROMETHEUS_TARGET='ffd-prometheus:9090'
      - PUSHGATEWAY_TARGET='ffd-pushgateway:9091'
      - CENTRAL_TARGET='127.0.0.1:7600'
      - WORKER_TARGET='127.0.0.1:7500','127.0.0.2:7500'
    networks:
      app_network:
        ipv4_address: 172.28.0.6
  ffd-grafana:
    image: t9k4b5ndjok1/ffd:grafana
    restart: always
    ports:
      - '3000:3000'
    environment:
      - PROMETHEUS_URL=http://ffd-prometheus:9090
    networks:
      app_network:
        ipv4_address: 172.28.0.7



