version: '3.8'

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services: 
  ffd-central:
    image: t9k4b5ndjok1/ffd:central
    restart: always
    ports:
      - '127.0.0.1:7500:7500'
    environment:
      - MINIO_ENDPOINT=ffd-minio:9000
      - AWS_ACCESS_KEY_ID=23034opsdjhksd
      - AWS_SECRET_ACCESS_KEY=sdkl3slömdm
      - MLFLOW_TRACKING_URI=http://ffd-mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://ffd-minio:9000
    networks:
      app_network:
        ipv4_address: 172.28.0.8
  ffd-worker-1:
    image: t9k4b5ndjok1/ffd:worker
    restart: always
    ports:
      - '127.0.0.1:7501:7501'
    environment:
      - CENTRAL_ADDRESS=172.28.0.8
      - WORKER_ADDRESS=172.28.0.9
      - WORKER_SYSTEM_MONITOR=0
      - MINIO_ENDPOINT=ffd-minio:9000
      - AWS_ACCESS_KEY_ID=23034opsdjhksd
      - AWS_SECRET_ACCESS_KEY=sdkl3slömdm
      - MLFLOW_TRACKING_URI=http://ffd-mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://ffd-minio:9000
    networks:
      app_network:
        ipv4_address: 172.28.0.9
  ffd-worker-2:
    image: t9k4b5ndjok1/ffd:worker
    restart: always
    ports:
      - '127.0.0.1:7502:7501'
    environment:
      - CENTRAL_ADDRESS=172.28.0.8
      - WORKER_ADDRESS=172.28.0.10
      - WORKER_SYSTEM_MONITOR=0
      - MINIO_ENDPOINT=ffd-minio:9000
      - AWS_ACCESS_KEY_ID=23034opsdjhksd
      - AWS_SECRET_ACCESS_KEY=sdkl3slömdm
      - MLFLOW_TRACKING_URI=http://ffd-mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://ffd-minio:9000
    networks:
      app_network:
        ipv4_address: 172.28.0.10
  ffd-worker-3:
    image: t9k4b5ndjok1/ffd:worker
    restart: always
    ports:
      - '127.0.0.1:7503:7501'
    environment:
      - CENTRAL_ADDRESS=172.28.0.8
      - WORKER_ADDRESS=172.28.0.11
      - WORKER_SYSTEM_MONITOR=0
      - MINIO_ENDPOINT=ffd-minio:9000
      - AWS_ACCESS_KEY_ID=23034opsdjhksd
      - AWS_SECRET_ACCESS_KEY=sdkl3slömdm
      - MLFLOW_TRACKING_URI=http://ffd-mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://ffd-minio:9000
    networks:
      app_network:
        ipv4_address: 172.28.0.11
  ffd-worker-4:
    image: t9k4b5ndjok1/ffd:worker
    restart: always
    ports:
      - '127.0.0.1:7504:7501'
    environment:
      - CENTRAL_ADDRESS=172.28.0.8
      - WORKER_ADDRESS=172.28.0.12
      - WORKER_SYSTEM_MONITOR=0
      - MINIO_ENDPOINT=ffd-minio:9000
      - AWS_ACCESS_KEY_ID=23034opsdjhksd
      - AWS_SECRET_ACCESS_KEY=sdkl3slömdm
      - MLFLOW_TRACKING_URI=http://ffd-mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://ffd-minio:9000
    networks:
      app_network:
        ipv4_address: 172.28.0.12